name: cajero
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  awesome_card: ^1.1.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^14.2.6
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5
  serverpod_postgres_pool: ^2.1.1
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
